//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprunts
    {
        public int IdEmprunts { get; set; }
        public int LivreId { get; set; }
        public int MembreId { get; set; }
        public System.DateTime DateEmprunt { get; set; }
        public System.DateTime DateRetour { get; set; }
    
        public virtual Livre Livre { get; set; }
        public virtual Membres Membres { get; set; }
        public string affichage()
        {
            string s = "";
            s += "                      Numéro d'emprunt : " + IdEmprunts + "\n";
            s += "\nInformation du Livre \n";
            s +="       "+ Livre.affichage()+"\n";
            s += "\nInformation du Membre \n";
            s += "        " + Membres.affichage() + "\n";
            return s;
        }
    }
}
