//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livre()
        {
            this.Emprunts = new HashSet<Emprunts>();
        }
    
        public int IdLivre { get; set; }
        public string Titre { get; set; }
        public string Auteur { get; set; }
        public string Isbn { get; set; }
        public System.DateTime DatePublication { get; set; }
        public string Genre { get; set; }
        public string Statut { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> nbEmprunt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunts> Emprunts { get; set; }
        public virtual Genre Genre1 { get; set; }
        public string affichage()
        {
            string s = "";
            s += "livre : " + this.IdLivre + "\n";
            s += "Titre : " + this.Titre + "\n";
            s += "Auteur : " + this.Auteur + "\n";
            s += "Isbn : " + this.Isbn + "\n";
            s += "Date de publication : " + this.DatePublication + "\n";
            s += "Genre : " + this.Genre + "\n";
            s += "Statut : " + this.Statut + "\n";
            s += "Nombre d'emprunts : " + this.nbEmprunt;
            return s;
        }
    }
}
