//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membres()
        {
            this.Emprunts = new HashSet<Emprunts>();
        }
    
        public int IdPersonne { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse { get; set; }
        public string Telephone { get; set; }
        public string email { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprunts> Emprunts { get; set; }
        public string affichage()
        {
            string s= "";
            s += "Numero du membre : " + IdPersonne + "\n";
            s += "Nom du membre : " + Nom + "\n";
            s += "Prénom du membre : " + Prenom + "\n";
            s += "Adresse du membre : " + Adresse + "\n";
            s += "Téléphone du membre : " + Telephone + "\n";
            s += "Email du membre : " + email + "\n";
            s += "Nombre de livre emprunté : " + this.Emprunts.Count+"\n";
            s += "Liste des livres empruntés : \n";
            foreach(Emprunts emprunt in Emprunts)
            {
                s += "        " + emprunt.Livre.Titre + "\n";
            }
            return s;
        }
    }
}
